name: Run Rust Syntax, Style, Format, and Integration Tests
runs:
  using: composite
  steps:
    # - shell: bash
    #   run: |
    #     : Set Rust terminal color configuration
    #     echo "CARGO_TERM_COLOR=always" >> $GITHUB_ENV
    - name: Install Rust + components
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.94
        components: rustfmt,clippy
    - name: Install code coverage
      uses: taiki-e/install-action@cargo-llvm-cov
    - shell: bash
      run: |
        : Run syntax and style tests
        cargo clippy --no-default-features --features=test --all-targets -- -D warnings
    - shell: bash
      run: |
        : Run format test
        cargo fmt --check
    # debug
    # - shell: bash
    #   env:
    #     RUST_BACKTRACE: full
    #   run: |
    #     : Run single orchestrator test to generate output images
    #     sha256sum tests/extra/data/output/*
    #     mkdir -p tests/.tmp
    #     cargo test --no-default-features --features=test --package=orcapod --test orchestrator -- --exact --nocapture offline_container_image_basic || true
    #     ls -la /tmp/*.png
    #     sha256sum /tmp/*.png
    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: segment_images_${{ runner.arch }}
    #     path: /tmp/*.png
    #     retention-days: 1
    # debug
    - shell: bash
      env:
        RUST_BACKTRACE: full
        # CARGO_TERM_COLOR: always
      run: |
        : Run integration tests w/ coverage report
        mkdir -p tests/.tmp
        cargo llvm-cov \
          --no-default-features \
          --features=test \
          --ignore-filename-regex "bin/.*|lib\.rs" \
          --cobertura \
          --output-path target/llvm-cov-target/cobertura.xml \
          -- \
            --color always
            --nocapture
