name: Run Rust Syntax, Style, Format, and Integration Tests
runs:
  using: composite
  steps:
    - name: Install Rust + components
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.94
        components: rustfmt,clippy
    - name: Install code coverage
      uses: taiki-e/install-action@cargo-llvm-cov
    - shell: bash
      run: |
        : Run syntax and style tests
        cargo clippy --no-default-features --features=test --all-targets -- -D warnings
    - shell: bash
      run: |
        : Run format test
        cargo fmt --check
    - shell: bash
      env:
        RUST_BACKTRACE: full
      run: |
        : Run integration tests w/ coverage report
        mkdir -p tests/.tmp
        cargo llvm-cov \
          --no-default-features \
          --features=test \
          --ignore-filename-regex "bin/.*|lib\.rs" \
          --cobertura \
          --output-path target/llvm-cov-target/cobertura.xml \
          -- \
            --color always \
            --nocapture
