[package]
name = "orcapod"
version = "0.1.0"
edition = "2021"
license = "MIT license"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
sha2 = "0.10.8"
glob = "0.3.1"
regex = "1.11.0"