name: Tests
on:
  - pull_request
jobs:
  diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Diagram
        uses: ./.github/actions/build-diagram
  rust-amd64-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Rust Syntax, Style, Format, and Integration Tests
        uses: ./.github/actions/rust-syntax-style-format-and-integration-tests
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: target/llvm-cov-target/cobertura.xml
          verbose: true
  rust-arm64-tests:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Run Rust Syntax, Style, Format, and Integration Tests
        uses: ./.github/actions/rust-syntax-style-format-and-integration-tests
  python-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, dependencies, and orcapod
        run: |
          set -e
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv -p 3.10 ~/.local/share/base
          uv pip install cffi maturin[patchelf] -p ~/.local/share/base
          uv pip install eclipse-zenoh -p ~/.local/share/base
          . ~/.local/share/base/bin/activate
          maturin develop --uv
      - name: Run smoke test
        env:
          RUST_BACKTRACE: full
        run: |
          . ~/.local/share/base/bin/activate
          python tests/extra/python/smoke_test.py -- tests/.tmp
      - name: Run agent test
        env:
          RUST_BACKTRACE: full
        run: |
          . ~/.local/share/base/bin/activate
          python tests/extra/python/agent_test.py -- tests/.tmp
